[tox]
min_version = 4.0
env_list =
    py313
    type
    lint
    format
    security
    basedpyright

[testenv]
description = run the tests with pytest
package = wheel
wheel_build_env = .pkg
setenv =
    TERM = xterm-256color
package_env = .pkg
skip_install = true
commands =
    uv sync --dev
    pytest {tty:--color=yes} {posargs}

[testenv:type]
description = run type checks
skip_install = true
commands =
    uv sync --dev
    mypy {posargs:src/alpha_hwr}

[testenv:lint]
description = run linters
skip_install = true
commands =
    uv sync --dev
    ruff check {posargs:.}

[testenv:security]
description = run security checks
skip_install = true
commands =
    uv sync --dev
    bandit -r src/alpha_hwr -ll
    safety check

[testenv:basedpyright]
description = run basedpyright type checks
skip_install = true
commands =
    uv sync --dev
    basedpyright {posargs:src/alpha_hwr}

[testenv:format]
description = format code with ruff
skip_install = true
commands =
    uv sync --dev
    ruff format {posargs:.}
