[tox]
min_version = 4.0
env_list =
    py313
    type
    lint
    basedpyright

[testenv]
description = run the tests with pytest
package = wheel
wheel_build_env = .pkg
setenv =
    TERM = xterm-256color
deps =
    pytest>=6.0
    pytest-asyncio
    pytest-cov
    pytest-benchmark
commands =
    pytest {tty:--color=yes} {posargs}

[testenv:type]
description = run type checks
deps =
    mypy
commands =
    mypy {posargs:src/alpha_hwr}

[testenv:lint]
description = run linters
deps =
    ruff
commands =
    ruff check {posargs:.}

[testenv:basedpyright]
description = run basedpyright type checks
deps =
    basedpyright
commands =
    basedpyright {posargs:src/alpha_hwr}
